# Generated by Django 5.2.5 on 2025-08-12 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FleetVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('total_count', models.IntegerField(default=0)),
                ('active_count', models.IntegerField(default=0)),
                ('special', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0, help_text='Determines the display order')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
