# Generated by Django 5.2.5 on 2025-08-12 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_fleetvehicle'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fleet_type', models.CharField(default='Eka 7', max_length=100, unique=True)),
                ('total_distance', models.CharField(default='0 km', max_length=50)),
                ('co2_savings', models.CharField(default='0 kg', max_length=50)),
                ('avg_energy_consumption', models.CharField(default='0 kWh', max_length=50)),
                ('run_time', models.CharField(default='0 hrs', max_length=50)),
                ('traction_energy', models.CharField(default='0 units', max_length=50)),
                ('regen_energy', models.CharField(default='0 units', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rating', models.CharField(default='0.0', max_length=10)),
                ('speed', models.IntegerField(default=0)),
                ('soc', models.IntegerField(default=0)),
                ('range', models.IntegerField(default=0)),
                ('temp', models.IntegerField(default=0)),
                ('address', models.CharField(max_length=255)),
                ('summary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='users.vehiclesummary')),
            ],
        ),
    ]
