# Generated by Django 5.2.5 on 2025-08-12 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_vehiclesummary_vehicle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='profile_picture',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='fleetvehicle',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vehiclesummary',
            name='regen_energy',
            field=models.CharField(default='0 MWh', max_length=50),
        ),
        migrations.AlterField(
            model_name='vehiclesummary',
            name='traction_energy',
            field=models.CharField(default='0 MWh', max_length=50),
        ),
    ]
