# Generated by Django 5.2.5 on 2025-08-12 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='profile_picture',
        ),
        migrations.CreateModel(
            name='VehicleRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=100, unique=True)),
                ('vehicle_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='users.vehicletype')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleChartData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('battery_data', models.JSONField(default=dict)),
                ('temperature_data', models.JSONField(default=dict)),
                ('voltage_data', models.JSONField(default=dict)),
                ('current_data', models.JSONField(default=dict)),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chart_data', to='users.vehicleregistration')),
            ],
            options={
                'unique_together': {('registration', 'date')},
            },
        ),
    ]
