# Generated by Django 5.2.5 on 2025-08-12 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_vehicletype_remove_profile_profile_picture_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrailVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(max_length=100)),
                ('registration_no', models.CharField(max_length=100, unique=True)),
                ('fleet', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='range',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='rating',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='soc',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='speed',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='temp',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='vehiclesummary',
            name='avg_energy_consumption',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='vehiclesummary',
            name='co2_savings',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='vehiclesummary',
            name='fleet_type',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='vehiclesummary',
            name='regen_energy',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='vehiclesummary',
            name='run_time',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='vehiclesummary',
            name='total_distance',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='vehiclesummary',
            name='traction_energy',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='TrailDataPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('metrics', models.JSONField(default=dict)),
                ('ecu_data', models.JSONField(default=dict)),
                ('coordinates', models.JSONField(default=dict)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trail_data', to='users.trailvehicle')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
