# Generated by Django 5.2.5 on 2025-08-12 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_trailvehicle_alter_vehicle_range_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(max_length=100)),
                ('name', models.DateTimeField()),
                ('col2', models.CharField(max_length=50)),
                ('signal', models.CharField(max_length=50)),
                ('signal0', models.CharField(max_length=50)),
                ('signal1', models.CharField(max_length=50)),
                ('signal2', models.CharField(max_length=50)),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='users.vehicleregistration')),
            ],
            options={
                'ordering': ['-name'],
            },
        ),
    ]
