# Generated by Django 5.2.5 on 2025-08-13 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('superuser', 'Superuser'), ('fleet_owner', 'Fleet Owner'), ('sales', 'Sales'), ('service', 'Service')], default='fleet_owner', max_length=20),
        ),
    ]
