# Generated by Django 5.2.5 on 2025-08-19 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceStat',
            fields=[
                ('key', models.CharField(help_text="A unique key for the stat, e.g., 'total_distance'", max_length=100, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(help_text="The human-readable title, e.g., 'Total Distance'", max_length=100)),
                ('value', models.CharField(help_text="The value with units, e.g., '12,500 km'", max_length=100)),
                ('order', models.PositiveIntegerField(default=0, help_text='The display order on the dashboard')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AlterField(
            model_name='fleetvehicle',
            name='active_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fleetvehicle',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Display order on the dashboard'),
        ),
        migrations.AlterField(
            model_name='fleetvehicle',
            name='total_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
