name: Deploy to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Backend image
        uses: docker/build-push-action@v4
        with:
          context: ./eka_backend
          file: ./eka_backend/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/eka-backend:v1.0.1
            ${{ secrets.DOCKERHUB_USERNAME }}/eka-backend:${{ github.sha }}

      - name: Build and push Frontend image
        uses: docker/build-push-action@v4
        with:
          context: ./eka_sw_new
          file: ./eka_sw_new/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/eka-frontend:v1.0.1
            ${{ secrets.DOCKERHUB_USERNAME }}/eka-frontend:${{ github.sha }}

      - name: Set up kubeconfig
        run: |
          mkdir -p "$RUNNER_TEMP"
          # If your KUBECONFIG secret is base64 encoded, decode it, else write raw
          if echo "${{ secrets.KUBECONFIG }}" | base64 --decode &>/dev/null; then
            echo "${{ secrets.KUBECONFIG }}" | base64 --decode > "$RUNNER_TEMP/kubeconfig"
          else
            echo "${{ secrets.KUBECONFIG }}" > "$RUNNER_TEMP/kubeconfig"
          fi
          chmod 600 "$RUNNER_TEMP/kubeconfig"
          echo "KUBECONFIG=$RUNNER_TEMP/kubeconfig" >> $GITHUB_ENV

      - name: Verify Kubernetes cluster access
        run: |
          kubectl config current-context
          kubectl cluster-info
          kubectl get nodes

      - name: Deploy to Kubernetes
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Set the new image for the frontend deployment
            kubectl set image deployment/frontend-deployment frontend-container=${{ secrets.DOCKERHUB_USERNAME }}/eka-frontend:v1.0.1:${{ github.sha }}
            
            # Set the new image for the backend deployment
            kubectl set image deployment/backend-deployment backend-container=${{ secrets.DOCKERHUB_USERNAME }}/eka-backend:v1.0.1:${{ github.sha }}
            
            # Verify the rollout status
            echo "Verifying frontend deployment..."
            kubectl rollout status deployment/frontend-deployment
            
            echo "Verifying backend deployment..."
            kubectl rollout status deployment/backend-deployment
            
            echo "Deployment successful! ✨"
